package com.ur.web.robot.service.impl.service.program;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;


public class CodeForAdventTest {
	static class Dims {
		int first;
		int second;
		String character;
		String password;


		public static Dims of(String numbers, String character, String password) {
			String[] splitNumbers = numbers.split("-");
			int first = Integer.parseInt(splitNumbers[0]);
			int second = Integer.parseInt(splitNumbers[1]);
			String characterTrimmed = character.replace(":", "");
			return new Dims(first, second, characterTrimmed, password);
		}

		public Dims(int first, int second, String character, String password) {
			this.first = first;
			this.second = second;
			this.character = character;
			this.password = password;
		}

		public int getFirst() {
			return first;
		}

		public int getSecond() {
			return second;
		}

		public String getCharacter() {
			return character;
		}

		public String getPassword() {
			return password;
		}
	}

	String numbers = new String(
			"15-16#m:#mhmjmzrmmlmmmmmm\n" +
					"5-6#d:#dcdddhzld\n" +
					"3-4#s:#vqssdcbl\n" +
					"3-6#b:#bbhbbbqbbb\n" +
					"10-11#q:#cqqntqhqwwh\n" +
					"4-7#g:#ggkgggw\n" +
					"4-7#f:#fdfffflfvn\n" +
					"11-16#h:#thhrhrwhbshshsdhhhhr\n" +
					"7-12#n:#nnnnnnvnnnnn\n" +
					"4-5#f:#ffxfhldh\n" +
					"9-17#m:#mmmmmmmmjmmmmmmmw\n" +
					"2-5#h:#hqrfzhhh\n" +
					"4-7#x:#vxxfxxjxwvnlx\n" +
					"11-13#h:#dhhhhhhhdhhhrh\n" +
					"4-8#q:#qqphvphfrlqqkztgslzb\n" +
					"3-15#x:#htblqcbdxdzgvhszxz\n" +
					"4-5#j:#jjhnn\n" +
					"3-6#l:#bwkjllgcjrzhr\n" +
					"5-8#s:#ssmsspsss\n" +
					"1-15#d:#ddhmhmvlkppkbbdxbc\n" +
					"7-8#l:#ltllllllhgzlv\n" +
					"1-15#m:#mtmmmvmmbmmfmmkmmmm\n" +
					"1-3#x:#xrxzcxcx\n" +
					"5-6#t:#tttttdtv\n" +
					"2-5#x:#xxxxs\n" +
					"5-7#l:#gclqlml\n" +
					"5-10#g:#gggggggggn\n" +
					"6-9#j:#xwjjfngjgjsjsr\n" +
					"2-7#b:#hbqtchkcmblppvqp\n" +
					"16-17#j:#jjjjjjjjjjjjjjmjjj\n" +
					"1-5#p:#wpppdlpphppp\n" +
					"3-7#q:#mspqqqqq\n" +
					"1-4#k:#hkjk\n" +
					"3-6#l:#llbllldzf\n" +
					"11-14#x:#xxnxvxxxxlxxxkv\n" +
					"4-7#k:#zkkksmjmrzxftx\n" +
					"2-4#l:#lllwq\n" +
					"7-11#q:#tbqqmmvkrsz\n" +
					"3-4#f:#gwfs\n" +
					"3-5#z:#ztszz\n" +
					"2-4#k:#kkpzl\n" +
					"1-2#k:#kkwckkzwskgbdc\n" +
					"5-7#x:#mxxxdxf\n" +
					"1-3#p:#pppp\n" +
					"6-8#c:#rcqrmcqmpcc\n" +
					"5-6#s:#srgvwsc\n" +
					"5-6#w:#wwwwwww\n" +
					"2-6#w:#xwwzfwr\n" +
					"1-8#z:#djzzzcmz\n" +
					"10-14#b:#dbwbbbbbldtbbbrbbq\n" +
					"5-15#v:#wvzftvfvzkcvjdvvzcj\n" +
					"4-5#j:#lrjdmjj\n" +
					"1-15#q:#qqqqqqqqqqqqqqkqqq\n" +
					"1-2#w:#vwkw\n" +
					"2-4#c:#lccsfmkrnrldzbrc\n" +
					"5-14#r:#rcpghlsspmvwvzmpvl\n" +
					"7-9#n:#nnnnnnnnx\n" +
					"2-19#w:#wwwwwwwwwwwwwwwhwbww\n" +
					"6-7#r:#rrrrrzc\n" +
					"3-15#w:#mnxmfqgklqddfww\n" +
					"9-13#s:#tsslqtsszsqsssqssss\n" +
					"5-6#j:#jjjtjrb\n" +
					"8-9#f:#fffffffwfff\n" +
					"5-7#n:#nnnnnnhn\n" +
					"8-17#d:#dnfdqvwngbddvbndbsf\n" +
					"13-14#v:#vvvvvvvvtvvvvt\n" +
					"2-3#h:#hsbnhhhs\n" +
					"2-4#g:#ggcgm\n" +
					"2-7#r:#rvrrrrrvr\n" +
					"6-9#n:#qpxchngsbhxrgqdgbqs\n" +
					"4-8#k:#kkkkkkkkd\n" +
					"1-6#v:#mrvlldzv\n" +
					"7-10#w:#vvwkwrbnwczwww\n" +
					"10-14#k:#kkkknkkkkpkkkdmkh\n" +
					"9-10#s:#qqbwmssnssjs\n" +
					"5-6#z:#bzvdjz\n" +
					"6-13#j:#jjjjrzbrjzjmjzjsk\n" +
					"1-6#k:#kkkkkrsskk\n" +
					"8-10#v:#vvvvvvwvvzvb\n" +
					"10-12#m:#mmmmmmmmmdmm\n" +
					"9-10#k:#kkkkkkkkjkk\n" +
					"2-8#b:#pbcsbbprc\n" +
					"6-7#x:#xxxxnpxxxk\n" +
					"3-7#l:#llllllml\n" +
					"4-10#j:#jrjzjjjcjx\n" +
					"4-5#g:#gggmgg\n" +
					"14-15#n:#nnnndnnxnnnnntnn\n" +
					"4-6#h:#hzqpgbhwh\n" +
					"4-6#b:#plzbkbrpscqbxl\n" +
					"5-13#m:#hptczmkkmplmw\n" +
					"7-8#r:#vjhrhrkdrrrk\n" +
					"3-4#q:#qqqq\n" +
					"11-13#s:#sssnssssssmsss\n" +
					"11-13#x:#xxbhkwvvxgxjh\n" +
					"1-2#f:#ftlrdz\n" +
					"1-3#d:#mdslnl\n" +
					"2-10#r:#xrzbqcxlvtlrsznplk\n" +
					"8-10#w:#wwwwmwwtww\n" +
					"2-10#r:#zbzplcvnvrr\n" +
					"5-16#c:#lcccccclcccgcccccc\n" +
					"3-7#w:#wwpwwbww\n" +
					"1-4#s:#svsss\n" +
					"6-8#j:#jjllkwnjjjgcjpg\n" +
					"3-5#c:#cccbb\n" +
					"1-14#j:#jpkjjqjjgqmzbjjhjljj\n" +
					"4-9#w:#dwwlwwdmkww\n" +
					"7-8#p:#pppppppjhqp\n" +
					"1-14#d:#djmfmdddkhfqdzfdddd\n" +
					"2-3#r:#zrbjhpg\n" +
					"3-4#j:#jjkj\n" +
					"3-4#q:#qqqq\n" +
					"1-5#k:#kkkkwk\n" +
					"6-13#t:#ttzxtjtdjtmtttmtt\n" +
					"1-3#x:#jxvx\n" +
					"11-12#f:#fffffffffffkffffffff\n" +
					"4-5#l:#lllhlm\n" +
					"8-10#n:#hnnnnnkdfrnntdhnk\n" +
					"1-2#x:#gxxx\n" +
					"8-12#w:#pwwwwwwfwwww\n" +
					"1-19#p:#ppnxfswpxfpbfcpnnpq\n" +
					"10-11#h:#hhhphhhhhhgv\n" +
					"1-10#c:#dccbvcccccc\n" +
					"7-12#v:#vvvvvvrvdvvvvvvvvvvl\n" +
					"2-11#b:#jbncfdbbbbcb\n" +
					"3-4#n:#nnrn\n" +
					"3-12#s:#btnfjtszszssdrsd\n" +
					"3-7#b:#bznkfbb\n" +
					"5-6#r:#rhprrhrrrhnzjhr\n" +
					"6-18#n:#xznnnwwmwnvfnfnlhn\n" +
					"6-11#v:#smsvpcjvvgvtvkmvv\n" +
					"12-14#s:#sssssssssssssc\n" +
					"5-6#t:#ttttfx\n" +
					"7-9#p:#pppppnvppp\n" +
					"4-11#s:#fbvfqsswshlgr\n" +
					"10-11#n:#thnnnnvnnnnnvbnn\n" +
					"2-13#r:#dqnvjskcqhmrrtn\n" +
					"10-11#k:#kvhkskkfrkr\n" +
					"7-8#s:#sssssssm\n" +
					"5-6#d:#fddddvv\n" +
					"16-17#q:#qqmkfqvvqdqqckqrw\n" +
					"7-13#d:#lddrdgdddzddz\n" +
					"14-17#v:#vvvvvvvvvqrvvvvvbnqx\n" +
					"1-4#c:#ccqn\n" +
					"14-15#t:#tbtrrqgtldttmktrt\n" +
					"8-14#c:#csccctccrrcwcqc\n" +
					"1-4#n:#nnnbnnn\n" +
					"11-14#p:#pppppppppppppppppp\n" +
					"4-6#d:#hcrkddqddm\n" +
					"1-2#b:#xbbbb\n" +
					"2-7#f:#cfwqnzbtfnt\n" +
					"7-11#q:#qqqqkwqqlqqqq\n" +
					"2-7#g:#gtgsgwg\n" +
					"3-4#w:#wwks\n" +
					"2-6#j:#rjjstgwskhwc\n" +
					"8-15#w:#wwwwsgrwwhwjvgqw\n" +
					"5-6#f:#ffffhr\n" +
					"1-4#n:#kxcn\n" +
					"13-14#k:#kkkrkzkkkkkrkhq\n" +
					"2-4#d:#fdtpdlbp\n" +
					"4-5#g:#ggggg\n" +
					"5-8#x:#skzrxxsxxhknxzxxxpnf\n" +
					"4-7#h:#ddhhbxnlhfb\n" +
					"4-15#q:#wqqlqqqrgqqqwqqqqqq\n" +
					"2-3#j:#jjwlnjb\n" +
					"7-13#k:#kkxkknjkkkkkksk\n" +
					"3-6#g:#ggmgggggggg\n" +
					"3-4#b:#bbgbbfd\n" +
					"5-7#j:#jjjjwjjj\n" +
					"4-5#x:#hvnhxhxxkzxzxc\n" +
					"2-8#r:#rlrrwrrrc\n" +
					"11-14#c:#ccgccrcccccbhccccm\n" +
					"1-5#f:#vfffffffffff\n" +
					"16-17#f:#fffffffffffffffff\n" +
					"5-8#n:#nwnnngppnn\n" +
					"10-12#m:#mmmmmmmmmvmmm\n" +
					"7-9#l:#llllllgll\n" +
					"12-16#v:#vvvvvvvvvvvlvvvvv\n" +
					"10-12#w:#wwwwwxvwwjwwdwwwq\n" +
					"2-8#x:#cxjlkdwctx\n" +
					"10-11#d:#mdddlndmsdd\n" +
					"1-3#h:#bhkfwhjls\n" +
					"6-9#c:#cccpcncccc\n" +
					"1-4#c:#tzxzctxhpt\n" +
					"10-13#m:#mmmsmwmmmsmmcmh\n" +
					"8-9#k:#kkkdkkkrb\n" +
					"3-5#x:#xkxjxx\n" +
					"6-7#q:#cqmxqqqlhtqpgqsqwqqd\n" +
					"5-7#g:#ggzggggqg\n" +
					"2-4#n:#ncnvzvrk\n" +
					"6-7#k:#kkkkkzk\n" +
					"3-7#n:#nnnjcmpgtgxqdwjz\n" +
					"3-6#m:#zzzvmmmmlmq\n" +
					"1-4#q:#nqqqqq\n" +
					"4-5#n:#cnnzvn\n" +
					"4-8#s:#bscfsnss\n" +
					"8-9#b:#pqbtmxfbt\n" +
					"4-13#h:#shqjphgfvkrrj\n" +
					"3-8#n:#cnphjnhbtndtcn\n" +
					"11-12#f:#ffkfzfffbftfffff\n" +
					"6-8#p:#ppwppxspppbp\n" +
					"4-5#d:#ddddnddd\n" +
					"4-8#n:#qnbhwnzxd\n" +
					"3-8#r:#csflkrvrq\n" +
					"7-9#z:#zzwtzzmzzzzzxdb\n" +
					"4-7#f:#wgfffkw\n" +
					"3-6#d:#wgmxddvdwtdtknvsz\n" +
					"6-17#w:#mzmwwwwzkxwwcvpwrs\n" +
					"1-8#b:#bbnltzsmbbfp\n" +
					"2-5#z:#tpztzz\n" +
					"6-10#w:#rwtwrvwpwwwwpx\n" +
					"11-15#s:#sdsssssdsxlpsss\n" +
					"12-14#s:#sssvsssssssssr\n" +
					"10-11#x:#dqxfvxxxxlx\n" +
					"6-7#z:#zqzzzlzz\n" +
					"1-2#t:#ftvbp\n" +
					"10-15#d:#dddddddddmwdddshdd\n" +
					"8-16#w:#wwwfbwwfqwzwvwthjw\n" +
					"6-7#x:#xxxxxxpx\n" +
					"11-13#h:#hchhhhhhmhfhp\n" +
					"8-11#m:#vmmmkmmmxvmmmt\n" +
					"12-18#w:#jwmpwwwdwwwwkwswdwz\n" +
					"4-9#f:#hwfftvxmpfffff\n" +
					"1-5#n:#nhchnnkpn\n" +
					"2-16#l:#nlxtpcdlzdkhnmqsvqfg\n" +
					"4-5#r:#rrrrr\n" +
					"14-16#d:#dddddpgdrddddcdbddd\n" +
					"4-5#j:#gskjzxjjz\n" +
					"13-15#s:#qsmccrpnsrrvwsk\n" +
					"16-17#f:#ffffffflfffffffff\n" +
					"14-15#l:#nllcllllvnlwltll\n" +
					"3-4#g:#gxghgggdggg\n" +
					"5-10#x:#xfxxqljxxkxxx\n" +
					"1-4#q:#lmzzq\n" +
					"13-17#x:#xxxxxxxxxxxxxxxxt\n" +
					"8-12#b:#bbbmxbbbjbbbb\n" +
					"14-19#x:#glxxxxhxxxxwxjxxxxc\n" +
					"6-19#d:#ndflnddcxksdzdbwdddt\n" +
					"3-9#c:#ccccccccl\n" +
					"2-17#z:#zrxzbzwzzzzzfzzcz\n" +
					"1-4#m:#fmmmml\n" +
					"9-17#l:#lllllllllllllbllllll\n" +
					"7-10#r:#wgrnrkxrrmrprxrr\n" +
					"2-3#f:#vcfff\n" +
					"12-15#t:#tttttttttttwtttt\n" +
					"1-7#c:#xcccccc\n" +
					"1-9#t:#kftttbttchttttttttt\n" +
					"1-4#c:#cpkcwmdwxnwvjzfbj\n" +
					"12-16#n:#nnnnnnnnlnnnnnnnn\n" +
					"3-4#q:#qcjq\n" +
					"4-6#t:#tdttkshpmlgqstpttfcc\n" +
					"3-4#j:#jjmcxlb\n" +
					"3-19#w:#qwdwwhwwjqmwwwwgqwfw\n" +
					"7-12#z:#zzgzzzwzkzzb\n" +
					"14-15#c:#nccccbdqwdccccd\n" +
					"2-4#k:#kkkkrv\n" +
					"14-15#k:#kkkkkkkkkkkkkkrkkkk\n" +
					"3-14#s:#sspsssssssssstsssss\n" +
					"2-6#r:#tdrrrwcrrcrr\n" +
					"1-2#g:#gfgg\n" +
					"4-7#z:#zczhzkzzccmpg\n" +
					"3-8#t:#ttvtscttzcxtt\n" +
					"3-7#q:#svkxfrxrvqqpmxzsbk\n" +
					"17-18#p:#ppnppppppppppppppb\n" +
					"15-16#b:#brbbbbbbbbbbbbpbb\n" +
					"2-4#x:#shxx\n" +
					"6-15#m:#mmmmmmmmmmmmmmvm\n" +
					"3-4#b:#bbbbb\n" +
					"8-10#k:#kgkmkkkjkkgkkmk\n" +
					"9-12#j:#jtjlwjjjjjml\n" +
					"3-4#w:#whwdpqfwghhj\n" +
					"12-13#s:#ssssssssssssg\n" +
					"13-19#n:#nwdnntnnnqnnqnrbmnmn\n" +
					"14-18#z:#zzzzzzzzzzhzzzzzzl\n" +
					"4-11#b:#bbbbbbbbbbhbbb\n" +
					"3-19#x:#jwxjftcjnkmlgcfgxzmj\n" +
					"6-11#x:#xxxxxxxzxmxx\n" +
					"2-4#g:#vqgg\n" +
					"5-6#b:#bbtbbvhpvbbm\n" +
					"7-9#t:#csthttrtttt\n" +
					"10-13#q:#qqqqnqgcqnqqqlqcq\n" +
					"8-10#j:#jjjjjjjdjw\n" +
					"9-10#v:#vrpnvvvvsvqvcvv\n" +
					"2-12#q:#jqqqqqwqqqkqkqqq\n" +
					"4-12#z:#zrcznzmzzwzzfs\n" +
					"3-6#n:#ntnptpnvnns\n" +
					"5-10#d:#ddddhddqdd\n" +
					"1-4#l:#pcdsl\n" +
					"4-5#d:#ddddz\n" +
					"3-10#v:#kgnvtcvfvvqkvgwkvj\n" +
					"16-17#x:#pdpxctpsxgpjshbxvvq\n" +
					"2-11#k:#kkkskkkkkkz\n" +
					"1-4#d:#ddddm\n" +
					"3-4#b:#bbqm\n" +
					"4-7#b:#bbrbbbb\n" +
					"18-19#h:#hhhhhhhhhhhhhhhhbhwh\n" +
					"8-10#p:#pvlxpppbppppptqbwgp\n" +
					"1-3#w:#sfwgwnvghzrn\n" +
					"3-4#l:#llwlln\n" +
					"15-19#j:#jjjjjjjjjjjjjjbjjjjj\n" +
					"1-7#d:#ddddndddd\n" +
					"6-14#c:#ccccchcdcccccc\n" +
					"12-17#f:#ffxffjffhffzsffffffv\n" +
					"5-9#b:#pnbglbbbrdn\n" +
					"8-9#v:#vvvvvvfwvvqgc\n" +
					"5-10#l:#llklllgllzlm\n" +
					"2-5#t:#tttttt\n" +
					"3-7#f:#fsfhzcfffvffnrfv\n" +
					"2-5#q:#gqqqq\n" +
					"6-7#c:#ccccccj\n" +
					"9-13#g:#vrgjgkggvpggggggg\n" +
					"4-10#n:#nrqnnknbvntszznzmgbn\n" +
					"2-7#x:#wslrxrx\n" +
					"4-6#s:#ssszbwst\n" +
					"4-6#m:#mzmcgnm\n" +
					"6-8#g:#gdggggggg\n" +
					"3-6#q:#qqqqqknrq\n" +
					"16-17#d:#dddddddddddddddzd\n" +
					"4-11#b:#bbbpbbbbbbvb\n" +
					"3-4#p:#jrppp\n" +
					"2-7#n:#wgznngfndc\n" +
					"2-9#f:#kcfrnfcpknxfgj\n" +
					"11-14#l:#nvdlmzgpllqzllvlqlt\n" +
					"5-6#g:#ggggdsgg\n" +
					"15-17#r:#kqflshskjhrcgrfcr\n" +
					"13-17#f:#gpfwfffffffbfffffff\n" +
					"15-17#s:#srssfssshssgsstss\n" +
					"4-8#f:#fvfpfbffffb\n" +
					"11-16#w:#wwwwwwwwwwwwwwwr\n" +
					"3-4#j:#jhjvhwd\n" +
					"4-5#r:#rrqtrr\n" +
					"6-14#w:#dkwwqwdrxrwwbxwqgww\n" +
					"4-5#s:#sssgk\n" +
					"2-4#d:#ddtmxd\n" +
					"8-9#w:#wwwwwwwwn\n" +
					"2-15#d:#rhkgdbbzdszjmbm\n" +
					"2-7#h:#jvqmhwbhfqkgzw\n" +
					"6-12#q:#qtqqqfqqqqqd\n" +
					"3-5#g:#gsxcggzfwgggsl\n" +
					"2-7#p:#dprmlmpwpw\n" +
					"9-10#m:#mmmmmmmmmkmm\n" +
					"1-4#z:#zzzqkfzt\n" +
					"2-8#l:#llgllllb\n" +
					"3-12#w:#hwwcspbckppcgwb\n" +
					"2-3#s:#tnsxtstsstb\n" +
					"1-2#m:#fmsm\n" +
					"6-10#q:#qnqfqqqqqv\n" +
					"5-10#x:#tlgxxwcxgx\n" +
					"8-16#k:#kmkknmkgkkkkbkkkkkr\n" +
					"4-16#b:#nwbbfcfngbbspnxbj\n" +
					"2-9#m:#mmmnmvmvjxmmdmr\n" +
					"5-7#k:#fkkkjfbwfkk\n" +
					"2-4#m:#tmkfjfqqjmgsjmtz\n" +
					"3-15#z:#zzzzzzzzzzzqzzwzzzd\n" +
					"9-10#n:#dnnnnnxtnnnnnn\n" +
					"2-3#w:#wwwlcwzl\n" +
					"9-10#j:#mzbjvzjjvjjgrjj\n" +
					"3-4#d:#dhdd\n" +
					"2-6#r:#jrcrwjr\n" +
					"9-10#v:#bkvvvvvvvjvv\n" +
					"2-6#x:#xnwnnx\n" +
					"18-19#k:#kkkkkkkkkkkkkkkkkpk\n" +
					"3-5#j:#gtjrr\n" +
					"5-6#j:#jjjjjj\n" +
					"5-6#k:#kkzknk\n" +
					"12-15#t:#tttttttttbdlvtq\n" +
					"1-4#d:#ddwvz\n" +
					"3-8#f:#xlfffrpf\n" +
					"1-2#z:#zzdscgwbxtxrd\n" +
					"5-14#n:#nsnnnlnnznnxsnnnnnd\n" +
					"9-10#g:#gwslkgdgwqdbgws\n" +
					"4-6#f:#sfcgkffmfc\n" +
					"10-14#m:#dmmwlqmmmmmmmmnm\n" +
					"8-12#n:#nnnnnnnnvnnv\n" +
					"15-16#l:#lllllllllllllvqlf\n" +
					"1-10#t:#tftpttjtnt\n" +
					"2-7#t:#ljzdkxtwvbmjtff\n" +
					"2-9#w:#stwwlqcbtws\n" +
					"4-6#h:#hjwhhvvtpg\n" +
					"3-5#v:#vvgvv\n" +
					"8-12#d:#ddhcdpdjdddhddmr\n" +
					"10-11#x:#kxxllzjrdxlsxx\n" +
					"5-6#f:#fffjfrff\n" +
					"17-18#b:#bbbbbbbbbbbbhbbbbbbb\n" +
					"3-8#r:#znrntdqtmrg\n" +
					"6-12#s:#srsvsmsssssssssssss\n" +
					"2-13#z:#dzfvpthfxnpnz\n" +
					"7-13#j:#jjjjjjrjjcjjw\n" +
					"9-10#l:#tllllllljl\n" +
					"12-14#m:#mmmmmmmmmmmmmm\n" +
					"17-18#l:#llllllllqlllllllggl\n" +
					"1-9#d:#dkmqddddzdnrfckdz\n" +
					"6-7#m:#gmmmmmlh\n" +
					"13-15#t:#ttttxtttttttggbt\n" +
					"6-7#j:#jmzvwkjjnjsnjkjxj\n" +
					"1-17#m:#gmmnmdvfmmtmmqmmzcj\n" +
					"3-5#l:#hvxsjt\n" +
					"7-8#x:#kxqczpdxfpjp\n" +
					"2-5#k:#kgkkhkdkk\n" +
					"5-7#v:#nbjvcgsvf\n" +
					"8-9#d:#cxddddnsxd\n" +
					"2-3#p:#mmqnjbtbpnmp\n" +
					"11-12#m:#jmmmmwvmmhtmmmmlmm\n" +
					"3-14#m:#zmmjsqfmqrnzmlmwrjm\n" +
					"3-6#n:#vnnnnjn\n" +
					"11-12#j:#jjjjjjjcjjjs\n" +
					"13-17#r:#rrrrrrrrrrrrrrrrrr\n" +
					"4-5#c:#bcncn\n" +
					"2-3#j:#bjftxcnzpnjrzxhxlp\n" +
					"9-12#z:#tzrlxlzdxzsz\n" +
					"3-5#j:#sjtltj\n" +
					"5-7#w:#wwwwwww\n" +
					"5-7#p:#ppzppcwkvwmwpscfpp\n" +
					"9-10#j:#jcjjjjjjjj\n" +
					"3-4#m:#mmrm\n" +
					"1-10#k:#zkkktkkkkk\n" +
					"5-13#d:#bpfldtnfrbdfk\n" +
					"2-3#s:#zsskw\n" +
					"6-12#x:#xxxxxkxxbxjxlzx\n" +
					"3-9#t:#ntgdtbtwnntjbcsfz\n" +
					"6-10#j:#sndjqjjdjbfjc\n" +
					"3-4#t:#ckqtjtffctwtcp\n" +
					"2-3#v:#wvhffpnngzv\n" +
					"7-8#r:#tlrncrsg\n" +
					"7-10#g:#gjggkfvffg\n" +
					"4-9#x:#xpxlxxxmpr\n" +
					"6-9#r:#srrrprrrr\n" +
					"7-10#v:#gvvnnvhvvvvvdjjvv\n" +
					"4-6#s:#psnsgsnfxlscwss\n" +
					"2-4#w:#vwwpwx\n" +
					"2-4#b:#bbbb\n" +
					"2-16#v:#vvvvvvvvvmdvvvvv\n" +
					"3-5#f:#ffkffjffff\n" +
					"6-9#q:#lqqqqjqqxn\n" +
					"1-5#w:#qcvwwwhw\n" +
					"2-10#w:#wwwwwwwkjz\n" +
					"6-8#t:#tttttttz\n" +
					"13-14#x:#xxdxxxhbxxxgcdx\n" +
					"2-4#n:#svkl\n" +
					"8-14#f:#fffffcfffffffnffw\n" +
					"3-6#n:#lsnnnpnnn\n" +
					"11-13#l:#lllllllblllll\n" +
					"4-5#s:#sssss\n" +
					"3-4#z:#zbzt\n" +
					"1-4#x:#xxxsx\n" +
					"8-9#c:#wlxctcccrqccsccr\n" +
					"5-8#v:#vvnvndfqq\n" +
					"4-6#r:#rrrtrc\n" +
					"10-15#b:#nbbbpfbbbcbzzxbf\n" +
					"4-5#s:#sglpschlsgsqbskrd\n" +
					"13-17#k:#bvfzktkkkzkkjkkwkf\n" +
					"1-11#x:#zkxxxgxxkwxvxgx\n" +
					"15-16#d:#dddddddddddddgdwd\n" +
					"2-3#p:#pzpprsp\n" +
					"16-19#s:#sssbssscjsshwmmszst\n" +
					"11-13#s:#stsssssssgmssp\n" +
					"10-11#s:#sssssssssgs\n" +
					"5-8#j:#jjjjttkj\n" +
					"9-12#s:#ssssgsssswsv\n" +
					"16-17#k:#kkkkkkkkkkkkkkkwb\n" +
					"9-10#g:#bzcdgvrvqg\n" +
					"4-5#n:#nnnrn\n" +
					"4-12#n:#knnrnnxnnnnjndwn\n" +
					"1-3#m:#mtmspm\n" +
					"16-17#b:#bbbbbbbbbbbbbbbxb\n" +
					"9-14#m:#mmdmqwwbmmlxmjljmm\n" +
					"6-11#z:#wzzzzzzzzzzzzszxzvz\n" +
					"2-8#q:#qqqqrqqqq\n" +
					"3-4#f:#ffhf\n" +
					"9-12#t:#ttlqqthvttcttttm\n" +
					"5-8#w:#zwwwwlmwwlww\n" +
					"5-7#z:#zjjwzkkkjlwzvkp\n" +
					"7-10#z:#zkzgzzzxtzz\n" +
					"12-13#v:#vvmvvklvvvvgv\n" +
					"10-14#t:#ttttttqttttsrttktv\n" +
					"7-10#l:#llhlllzllv\n" +
					"1-4#j:#blwjjmj\n" +
					"8-10#k:#qpffpqskqk\n" +
					"5-9#w:#wkdjxcwwswwwwwh\n" +
					"11-13#b:#bbbbbbbbbbgtjb\n" +
					"14-16#c:#ccccfcbccccccccccc\n" +
					"9-11#l:#lflnpwbcmld\n" +
					"8-11#q:#qqqqqqflqhtpqq\n" +
					"12-18#z:#zzzzzzzzzzzmzzzzzl\n" +
					"4-5#x:#xxfhxx\n" +
					"6-16#z:#tfrhztxxzzqczznwzz\n" +
					"4-13#l:#vlrlmlllldllq\n" +
					"14-15#b:#bbwbvbbhbbbbkvnbbbb\n" +
					"3-5#x:#frxxx\n" +
					"11-13#f:#ffbfffnfffjlffffff\n" +
					"5-6#d:#dkrdrgdd\n" +
					"6-8#g:#gggwglggvtkglg\n" +
					"1-5#s:#sqsnpp\n" +
					"2-4#b:#bxjnb\n" +
					"1-2#h:#hhfr\n" +
					"10-19#b:#tzbpbsbbbtbbbbbbbbbb\n" +
					"3-4#p:#pkmcpm\n" +
					"1-8#q:#qqqqtqcnqxkqb\n" +
					"13-15#s:#ssmssqssssssssts\n" +
					"4-6#q:#qqdsqrqq\n" +
					"9-13#z:#zzbzzzzpzzzzz\n" +
					"19-20#r:#xlrrrgrrrcrktrrhrrrc\n" +
					"9-14#q:#qzsrqqqjxwqqhqd\n" +
					"7-15#g:#ggggggsggggggggp\n" +
					"4-5#w:#wwwkq\n" +
					"7-15#h:#ghgpkphhzpmhjpwxq\n" +
					"15-17#v:#vcvvvdvvvvvvvpvvhv\n" +
					"1-2#j:#qjqbfwbj\n" +
					"3-9#c:#nvcwkcndt\n" +
					"14-15#c:#cccccccccpccgkclcc\n" +
					"5-6#p:#pppppp\n" +
					"12-14#h:#hxtxhthhshkrmh\n" +
					"1-2#q:#wqjqzqqk\n" +
					"14-15#f:#fffffffffffffbqf\n" +
					"7-8#j:#vjjjjjfh\n" +
					"7-12#p:#trzzppxpptpfp\n" +
					"13-18#w:#wwwwwwwmrwwwwwwkwwww\n" +
					"10-11#f:#rfffszjfsvn\n" +
					"9-17#l:#llllllmlllllllllkl\n" +
					"5-12#s:#xssssqssshsss\n" +
					"2-6#x:#fxxxsxbnx\n" +
					"4-6#n:#nnnnxhnn\n" +
					"10-11#g:#gggggggggqg\n" +
					"8-16#n:#nknsfcnnnqgnnnxsnfnj\n" +
					"4-7#n:#ndnnnnnn\n" +
					"8-9#q:#shqphcskmqjqvqqqq\n" +
					"9-10#r:#rrrrrjrrrrrr\n" +
					"16-18#z:#zfzzzrzzzzzzzzzzzhzz\n" +
					"2-13#g:#gkgggqggggggrgg\n" +
					"12-18#v:#vvvvvvvvvvvvvvvvvvv\n" +
					"3-4#s:#hssq\n" +
					"6-11#h:#kdwftsxqcnhph\n" +
					"16-17#t:#ttttttttttttttttt\n" +
					"6-11#f:#fffffdffffsfffffffff\n" +
					"10-14#p:#pppppjvpppppph\n" +
					"10-15#b:#bbpbbbbbbtbbbbb\n" +
					"3-7#n:#nnnnnnx\n" +
					"3-5#r:#rrffrsr\n" +
					"10-13#r:#brrrrrrrxrrrrr\n" +
					"6-7#f:#ffffkjf\n" +
					"3-7#r:#srdrrsrrfrcr\n" +
					"4-9#b:#gflbcxtvknsbpjbwrk\n" +
					"8-10#p:#pttpkfppcppdznpgpp\n" +
					"13-16#q:#qqqqqqqqqqqqqqtqs\n" +
					"1-4#r:#rrrwr\n" +
					"1-2#g:#zggggggggggg\n" +
					"7-8#j:#jjjjjjwb\n" +
					"18-20#t:#pwnrvbdzxntvgjjjltqn\n" +
					"8-13#f:#fffxffflffffff\n" +
					"4-5#k:#cklkk\n" +
					"10-11#m:#mmnmmmmmmnm\n" +
					"11-16#q:#qqqqqqsqqfsqzqqqq\n" +
					"2-9#n:#nnnnnnbnnc\n" +
					"7-11#d:#sddnmgfkdddzdd\n" +
					"1-4#f:#qfdlftk\n" +
					"8-10#p:#pzpppxphphpp\n" +
					"2-4#m:#mlwf\n" +
					"6-8#h:#jxhhhfztzh\n" +
					"5-8#s:#ssnnnssssstsssssd\n" +
					"3-5#x:#hlxsx\n" +
					"7-8#h:#qhhhhhhwdhph\n" +
					"2-7#v:#gxdvcvw\n" +
					"14-15#n:#nnnnnkhnfnnnfnnnnnn\n" +
					"9-10#l:#lllllllhlnklx\n" +
					"13-18#j:#jjjdjcljjjjjjjjjjhj\n" +
					"1-7#h:#jkhhhhhhj\n" +
					"9-19#z:#tzznzzztcbxkzvssrzzz\n" +
					"12-18#s:#sswssscsstnssjssss\n" +
					"4-9#z:#zzzxmzgkzspdmq\n" +
					"6-13#d:#ndldddpddddddkmdd\n" +
					"8-9#q:#zgqrkhxqq\n" +
					"3-6#m:#mmmgfdw\n" +
					"1-3#l:#dlls\n" +
					"10-11#b:#kbbbsbbdbkbqbbbbs\n" +
					"2-4#b:#bbbp\n" +
					"5-6#c:#xctccckq\n" +
					"3-5#k:#kkkkk\n" +
					"12-14#b:#bbbbbbzbbnqbbb\n" +
					"6-8#q:#jmmhqqlqqkgqcjvqq\n" +
					"11-12#g:#ggggpggggghsgg\n" +
					"8-9#h:#hhhhchhhbh\n" +
					"10-11#w:#zwwcfgwwwwc\n" +
					"5-8#x:#xxxxnxlxxx\n" +
					"1-4#f:#fffhf\n" +
					"2-3#f:#fbwfxr\n" +
					"5-6#f:#vrfffd\n" +
					"14-15#r:#lrrrrrrrrrrrrfc\n" +
					"7-8#t:#tbnptvtt\n" +
					"16-19#r:#rrgrrrrrrrrljrrrrrrr\n" +
					"2-4#b:#bbpsh\n" +
					"7-13#m:#gmmsmmlmmbmmmmmmmgkx\n" +
					"16-17#g:#ggggggggggggggrfgg\n" +
					"1-2#g:#fcfmr\n" +
					"5-7#l:#lclllll\n" +
					"3-5#n:#nnnccgvn\n" +
					"1-4#v:#npvv\n" +
					"5-11#s:#sshsxsswshss\n" +
					"9-12#x:#mxxkxxxxsxpkxsxhnktx\n" +
					"3-4#f:#fsff\n" +
					"5-11#b:#bqzzbcbbbxbk\n" +
					"3-7#s:#ssxsssv\n" +
					"6-14#p:#pxppjppppppvjp\n" +
					"2-4#h:#hhkch\n" +
					"5-7#s:#sdshspsssqs\n" +
					"2-8#k:#vwkkkkwkskjr\n" +
					"17-18#m:#mmmmmmmmmmmrmmmmzm\n" +
					"12-15#w:#nwrgwwwjpwwwwpv\n" +
					"3-4#t:#ttft\n" +
					"5-11#f:#kfffzffzfffk\n" +
					"15-16#d:#ddhddddddddcddddd\n" +
					"3-10#l:#wplpvlrcqwlblvlcqm\n" +
					"2-5#z:#zpzzz\n" +
					"3-5#v:#vvgvv\n" +
					"3-4#b:#jbgbb\n" +
					"14-15#d:#ddddddndddddddd\n" +
					"4-13#z:#zszfktzrzjtzzbmn\n" +
					"1-8#b:#xbbxrbbbbbb\n" +
					"3-4#t:#tttftt\n" +
					"5-9#v:#ptvvvcvvvvvnvvvv\n" +
					"1-2#n:#tcnnnnln\n" +
					"5-6#h:#hhhhhh\n" +
					"10-11#j:#jvjjhfjbxjj\n" +
					"4-7#t:#twtdttttttttt\n" +
					"12-16#z:#zzzzzzzzzwzzzwzzzzzz\n" +
					"7-18#l:#hnhcvlnxglxlldlfgvll\n" +
					"2-5#j:#jjjjjj\n" +
					"2-8#n:#nrknnntn\n" +
					"8-9#z:#zzzzzzzqz\n" +
					"4-5#z:#zzzzr\n" +
					"1-9#t:#bztttgtllwq\n" +
					"8-12#n:#ckjnntmkxxcnwkqznp\n" +
					"2-4#b:#xbrvvhbbb\n" +
					"1-4#d:#dddzqd\n" +
					"13-17#w:#wwlwvlwpwwdwwwwqb\n" +
					"3-5#q:#lqzmlq\n" +
					"8-9#z:#bpzzzczzpzz\n" +
					"1-6#n:#nbjqmnhxwh\n" +
					"6-8#q:#qqqqqqqzq\n" +
					"16-18#r:#rrrrrvrrrrnrrrrrrb\n" +
					"3-8#l:#lbfdwlpzmkl\n" +
					"2-3#g:#srwcwmgvzjjxj\n" +
					"8-17#w:#wwwwwwwjwwwwwwwwww\n" +
					"19-20#t:#tttttttttdttttttttvf\n" +
					"1-11#x:#pwnwxxfxnkxxtzpglx\n" +
					"6-7#g:#lgpglng\n" +
					"5-7#l:#llllfll\n" +
					"5-6#p:#ppppppp\n" +
					"3-4#x:#xxdf\n" +
					"4-15#l:#fgkzwrrpmvmhzplsqp\n" +
					"2-4#b:#bbqjb\n" +
					"4-6#k:#kbkkkwkkk\n" +
					"4-8#p:#mppzpprpp\n" +
					"14-17#n:#ttfvdtwxnnfdsnxbn\n" +
					"3-5#m:#mmzmmm\n" +
					"6-7#k:#kkkkndk\n" +
					"1-6#r:#hkkrln\n" +
					"4-6#h:#hhhhhmhhhhhhh\n" +
					"7-10#k:#kkkkkkkkksk\n" +
					"3-4#g:#fggggg\n" +
					"5-12#x:#qhgrxxhrxjjxxhxgb\n" +
					"3-5#x:#lxpxxb\n" +
					"4-7#f:#frffsfjff\n" +
					"4-6#d:#dpddjfxdrt\n" +
					"11-13#f:#fffpxfcfffdfnfzf\n" +
					"12-18#r:#rrrrwrrrrrwrrrcfrcr\n" +
					"18-19#q:#kqqqqqqqqqqqqnqqqkqq\n" +
					"3-4#b:#bgbrf\n" +
					"15-17#s:#ssssssssssssssbdss\n" +
					"6-9#d:#bnvlpxlctvdd\n" +
					"1-2#s:#smsss\n" +
					"2-9#s:#cpgrfdfmm\n" +
					"5-12#j:#jjjxdqjctjjtnzcjq\n" +
					"9-16#g:#xqzgsrdtcvblfpmg\n" +
					"11-15#q:#qqqsqqqqwdqqmqqpqh\n" +
					"3-8#d:#xddzddtdnk\n" +
					"5-8#p:#blppgpppppppx\n" +
					"7-9#m:#mqwlxbbcmqf\n" +
					"6-8#t:#ltttbttsbtrtts\n" +
					"12-13#k:#kqmfkcvkwsnddkk\n" +
					"16-17#t:#hrkwqdtckqdktgctj\n" +
					"2-4#m:#mmmm\n" +
					"2-11#l:#tlflzkxlvlq\n" +
					"5-6#j:#jjjjjl\n" +
					"2-13#x:#wzfjxsbqznqlx\n" +
					"4-8#s:#mssssfzpsh\n" +
					"7-17#v:#vvxvvvllvxvvvhrvvv\n" +
					"3-6#h:#qchchw\n" +
					"4-10#n:#nllnnbnrvnnnmgnzb\n" +
					"16-17#v:#vvvfvvvvvvvvpvvvjv\n" +
					"2-14#f:#lpbfwlffxhlxfffkf\n" +
					"5-7#w:#cfwkwnl\n" +
					"4-6#n:#nnnnnn\n" +
					"10-11#d:#dcddddddddd\n" +
					"1-2#d:#nvrdpnvnlxccjrd\n" +
					"15-16#v:#vvjvvvvvvvvvvvhzv\n" +
					"3-4#l:#wwlpllqk\n" +
					"2-4#p:#pvpp\n" +
					"2-3#b:#bmbf\n" +
					"2-12#m:#snpdndwgtfqjlzdmmth\n" +
					"5-8#j:#rpjjjjlpsj\n" +
					"5-9#g:#gdmvgsgjrhg\n" +
					"6-7#p:#pppppdspp\n" +
					"2-9#k:#dktlkrkwlnd\n" +
					"9-18#b:#bbxbbbbbrbbbzbbbbvb\n" +
					"5-9#t:#ttqdcwdjtwtqttttbc\n" +
					"8-10#d:#njdddddtddhd\n" +
					"4-12#r:#fkrfrrrrrrrgr\n" +
					"6-7#s:#ssskgxssbs\n" +
					"2-6#m:#mtmmmkmm\n" +
					"11-12#h:#hhhhjhhhhhgh\n" +
					"8-9#q:#kfqkscqnq\n" +
					"6-12#d:#sdpddmvdvdxdl\n" +
					"1-8#f:#cffzgfffkfff\n" +
					"4-9#v:#vvvvcnljw\n" +
					"4-5#p:#wplvpp\n" +
					"2-3#w:#kxwwww\n" +
					"3-5#m:#nmmmmm\n" +
					"2-6#t:#ttntttjhctkztt\n" +
					"11-14#v:#vvvvvvvvvvqvvf\n" +
					"7-8#z:#zzgjqzzzzzdzzkzw\n" +
					"13-15#k:#kkkkkkkkfkkkkkk\n" +
					"6-7#m:#mmmmmfmgm\n" +
					"7-8#m:#fgxsdqmnmmszv\n" +
					"1-3#p:#pqppp\n" +
					"8-12#s:#sssxqstsssnfsxss\n" +
					"7-10#q:#qqqfqqxqqqq\n" +
					"2-5#x:#djhvxxm\n" +
					"3-5#b:#bjbbbrjgbbxkbgpqd\n" +
					"3-17#c:#ccscccjccmclccccccc\n" +
					"8-12#d:#djrdgddwxddxskt\n" +
					"7-9#h:#hhhhhhzhmh\n" +
					"4-8#l:#jwlplsct\n" +
					"6-10#q:#qvqhqxnqqmz\n" +
					"1-5#w:#wwpwqw\n" +
					"3-12#d:#pltzkcsdhphdmdxkb\n" +
					"1-9#k:#kkkkkkkkx\n" +
					"2-6#d:#dbddqddd\n" +
					"11-13#n:#njnrjnnnnnqzn\n" +
					"2-4#k:#kkkkkk\n" +
					"11-14#g:#gggggggggggcgngg\n" +
					"15-19#v:#vxqvvvvvvvxvvvbvvvdv\n" +
					"9-10#s:#ssscsssssf\n" +
					"1-14#m:#mmmmfmpqmmmmml\n" +
					"6-8#t:#sttqtbtjt\n" +
					"5-7#k:#vkkshkw\n" +
					"5-7#x:#xscxxxm\n" +
					"6-12#d:#pddxdddqkdddzmddpd\n" +
					"2-14#t:#gtmxtcttqtttxtv\n" +
					"7-14#r:#rrrrrrrrrrrrrpr\n" +
					"15-17#d:#ddddfdddddddddddmd\n" +
					"4-5#x:#xqxxx\n" +
					"11-13#w:#wwwwwwwwwwfww\n" +
					"5-6#j:#jjjjjj\n" +
					"5-6#m:#mmmmmm\n" +
					"1-3#b:#fbblbbgbx\n" +
					"7-8#v:#vvvvvxvrvd\n" +
					"6-11#f:#ffffpwpfqfhfzxdc\n" +
					"11-17#m:#mtmdkbvmjmxmmdmmgb\n" +
					"8-12#h:#nhbtsbhjhgdh\n" +
					"7-11#w:#wwwpwwdwwwd\n" +
					"11-12#f:#hffrfffffffqqf\n" +
					"12-13#f:#flfcffffffffqdff\n" +
					"2-3#v:#hbbv\n" +
					"8-11#d:#drdlbdhwdsddd\n" +
					"6-9#w:#swrwnbwmkxwt\n" +
					"10-13#l:#llflsllllntlll\n" +
					"8-11#v:#xvvvvvtkmcvvvxh\n" +
					"3-4#h:#hzhbh\n" +
					"11-12#b:#bzbbbbbbbgzxbbbbbm\n" +
					"13-17#l:#lqwxqmqmjlsmfwltkzl\n" +
					"1-5#l:#mwllx\n" +
					"7-8#c:#cccnccxcc\n" +
					"6-12#b:#tbbsjbkprrdg\n" +
					"3-5#z:#zmpzc\n" +
					"5-8#j:#jjjltjjj\n" +
					"6-11#z:#xzlzgzqhqwgz\n" +
					"4-5#m:#mmmmmm\n" +
					"5-6#q:#pqwfqh\n" +
					"9-14#p:#pppppptfhpzjtct\n" +
					"6-10#w:#wdwwwlwwdww\n" +
					"14-17#m:#mmmmmsmmmmqmmwmmm\n" +
					"4-5#v:#vvhpfnvv\n" +
					"1-7#q:#qfqqbxqvqf\n" +
					"6-11#z:#zzzzzzzzzzd\n" +
					"6-13#g:#gggggfggggggg\n" +
					"12-13#d:#ddpdjqdddddmd\n" +
					"8-10#n:#nnndnnnnnn\n" +
					"6-7#z:#zzgdzzdvz\n" +
					"6-8#n:#vdnvnsnnnlnn\n" +
					"3-4#b:#bblbl\n" +
					"1-3#f:#zpfjkfr\n" +
					"7-9#h:#fhtxkhwhgq\n" +
					"7-9#x:#xxdxxxpxx\n" +
					"2-3#v:#vmxv\n" +
					"18-19#z:#zzzzzzzzzzzzzzzzzhrz\n" +
					"4-6#x:#hjlsdv\n" +
					"2-3#x:#jzxxvkhsxxck\n" +
					"1-9#s:#sfjvsjqvss\n" +
					"8-12#j:#xxcmpzjjtmkswwr\n" +
					"4-10#s:#ssjtvssslwszss\n" +
					"9-16#h:#rhhphhhhwwhhhgrhhh\n" +
					"7-8#h:#hvhhhhhzh\n" +
					"7-10#m:#mmmdqbtssvmfmmmgr\n" +
					"5-7#h:#hhbhzhh\n" +
					"5-10#c:#ccccqcwxcccc\n" +
					"4-6#q:#bmhqqbpfrqfdkq\n" +
					"7-9#r:#rcmrdrrrjlrscrrhkl\n" +
					"3-4#t:#ttgz\n" +
					"8-12#g:#mgggtggggzgzcphhx\n" +
					"6-8#d:#dvddfctd\n" +
					"2-3#g:#gmglf\n" +
					"1-2#m:#dmqwpbhmmktcvc\n" +
					"6-8#z:#bzwzzkxqpz\n" +
					"1-9#x:#xxxxbwvxcxxcxwznw\n" +
					"3-6#z:#zzzzzz\n" +
					"5-6#k:#kkkkhk\n" +
					"12-13#q:#zqqnrcqqqplqqndfg\n" +
					"9-12#l:#jdvxtbqblmllfbnlff\n" +
					"3-6#v:#vvkvvv\n" +
					"4-7#v:#xbtzjdvp\n" +
					"8-10#h:#hhmhhhhhhnmd\n" +
					"7-8#t:#ttktgqfzxrdxqf\n" +
					"4-5#g:#gggjf\n" +
					"6-9#q:#qqqqmmqqqqq\n" +
					"1-10#w:#rwjwwwwwrcw\n" +
					"9-13#b:#ssbbbcbbbbbbd\n" +
					"2-3#g:#bggggv\n" +
					"6-11#w:#wwwwfwwxwwww\n" +
					"5-9#p:#ppjppppzt\n" +
					"3-14#z:#gpzzzdzzjzzpzzzz\n" +
					"1-7#v:#vbbfvjz\n" +
					"2-5#q:#qdwczqqq\n" +
					"1-5#r:#rrrrhwtf\n" +
					"8-14#d:#dddddddtdddddddd\n" +
					"7-8#p:#ppppppzlp\n" +
					"5-6#s:#lbssnssss\n" +
					"1-8#q:#lqnpqqqqq\n" +
					"1-4#k:#rkqkkk\n" +
					"1-9#z:#zgkxmkmgqzg\n" +
					"1-5#b:#cbbbbbf\n" +
					"1-4#c:#dctcc\n" +
					"4-5#x:#sxxtl\n" +
					"2-8#m:#qmfqbfmlkkkjzhqjbxpd\n" +
					"8-16#h:#lhlghlcbqgsmjhbh\n" +
					"8-9#x:#xxxxxxxxx\n" +
					"10-11#l:#cvndhntlghk\n" +
					"8-11#d:#dddddddcddz\n" +
					"4-5#j:#jvjpjj\n" +
					"1-2#d:#bmhdpdr\n" +
					"1-4#j:#jnjcjnjtd\n" +
					"4-8#m:#djsvzshmxmgb\n" +
					"4-10#k:#bhpkgzksrkkqk\n" +
					"4-6#l:#lllllwlvwlglxqll\n" +
					"9-10#h:#hhhhhhhhhm\n" +
					"3-4#q:#qqsbq\n" +
					"7-9#l:#dlllllgllllszg\n" +
					"10-12#l:#lllllllllvlzl\n" +
					"1-5#k:#kkkkr\n" +
					"10-11#w:#wdwfkwwwwww\n" +
					"8-10#g:#rzswrffrqgdhgzm\n" +
					"3-5#z:#zzzzz\n" +
					"8-14#p:#pplxppppzprpdpjpppdp\n" +
					"6-11#g:#mkghrgcmhxggcpddvx\n" +
					"4-6#b:#sjwbqv\n" +
					"1-2#q:#qvpqlsqqqrnbp\n" +
					"8-20#w:#wwwwwwwwwwwwwwwwwwwg\n" +
					"12-15#m:#mmmmlmmmmmfwmmm\n" +
					"1-14#x:#xxxxvxsxxxxwcjxvxxx\n" +
					"11-14#g:#ggdggggggggggx\n" +
					"2-5#r:#xrqtf\n" +
					"10-12#q:#qqqvqcqjqjfqqxqqkqj\n" +
					"3-4#c:#cvszc\n" +
					"2-7#w:#mwwwwwvwx\n" +
					"6-8#r:#hrgrckfb\n" +
					"4-8#d:#ddddgxcznlnwdddd\n" +
					"1-4#c:#drhvzzc\n" +
					"3-14#n:#pfnjnnhpnppfnrbhz\n" +
					"3-4#n:#bnnnb\n" +
					"13-15#h:#hhhhhphhhhhthhgh\n" +
					"3-5#l:#lfllpmknmplx\n" +
					"1-12#c:#lcchctpccccccx\n" +
					"8-9#l:#lznsllwlbllmllzl\n" +
					"7-9#w:#wwwwqshnwkwwww\n" +
					"10-12#k:#zxkknkxkrkckkr\n" +
					"9-12#r:#rdrkbkgrrrrznrr\n" +
					"12-13#g:#ggggggvgggggr\n" +
					"2-5#g:#vgxggr\n" +
					"5-6#c:#cccthsc\n" +
					"2-3#t:#nptdqmfglpzdvwkspt\n" +
					"4-13#q:#qqsxdqqfngqqkqq\n" +
					"17-19#r:#rrrrrrrrrrrrrrrrxrf\n" +
					"7-11#t:#ttttmthttttt\n" +
					"1-5#l:#lllwl\n" +
					"8-12#x:#xxxxxxxbxxxwxxx\n" +
					"10-11#d:#dddddbfddddcdd\n" +
					"3-5#f:#lfffb\n" +
					"1-4#f:#ffff\n" +
					"1-9#s:#swdckstss\n" +
					"7-9#p:#pbfzppbmp\n" +
					"1-2#p:#xpqssm\n" +
					"6-16#h:#hlhhqdhhmhhhhhphhrh\n" +
					"4-5#b:#pbbgxbhqbzvnwxxb\n" +
					"7-10#n:#nrbdnnnwnnnlnn\n" +
					"1-2#r:#mspcrbgfqs\n" +
					"12-16#l:#rlvmtklhllrvljlllx\n" +
					"7-10#p:#mpppppprpmjs\n" +
					"6-7#g:#gpggwmggggv\n" +
					"1-4#q:#qqdqlqq\n" +
					"9-18#x:#xxxxxxxxtxxxxxfxxxx\n" +
					"2-4#h:#hhhshh\n" +
					"3-4#q:#qllq\n" +
					"5-11#g:#ggggggggggsg\n" +
					"1-4#r:#mrwbr\n" +
					"4-6#m:#knhmnm\n" +
					"13-14#p:#pppppppppppppp\n" +
					"9-12#v:#vvtvvvvfvztvvvxwqlg\n" +
					"11-13#r:#rrrrprrrrrzrr\n" +
					"7-11#z:#zzzzzzjzzzzz\n" +
					"17-19#d:#ddddddddddddddddjdd\n" +
					"4-5#c:#ccncdc\n" +
					"4-6#x:#gxxvqx\n" +
					"2-3#g:#ggpg\n" +
					"6-11#m:#blgvnmbxhpmxmb\n" +
					"2-15#w:#wvdwwfqjwqwvmfrzw\n" +
					"3-4#s:#ssdw\n" +
					"6-7#l:#mmllqlcllklxcml\n" +
					"16-17#l:#lllplllllllllllllnl\n" +
					"2-4#h:#qtwhwz\n" +
					"5-7#v:#xvvwfvfvv\n" +
					"4-10#k:#kkkkkkkkqkkk\n" +
					"5-6#f:#qzvvpf\n" +
					"4-11#d:#whhddttshzds\n" +
					"10-13#q:#qjlqqqqqpwqqgqq\n" +
					"11-12#w:#nwwwdmvwwwwk\n" +
					"4-8#l:#rlljllhljl\n" +
					"7-10#s:#sssssssssd\n" +
					"2-8#c:#qcgrtxrfccgc\n" +
					"7-8#n:#pnnngnnnvnwdnn\n" +
					"8-10#c:#cscckctxcrhgc\n" +
					"1-4#n:#ngnncrnn\n" +
					"6-12#t:#ztzqttbmtztpsnrnt\n" +
					"8-12#b:#bbbbbbbbbbbb\n" +
					"1-4#z:#czzzzzzz\n" +
					"1-2#k:#kktmkf\n" +
					"10-14#x:#xxxjsxxnxxxxxqxxpx\n" +
					"11-15#v:#vxvvrvvvdvvvvvbv\n" +
					"7-9#s:#nsslmtsdxbxfsfssswfx\n" +
					"12-15#l:#lllllllllllfcltllll\n" +
					"6-7#q:#qqqqtqdqq\n" +
					"15-19#n:#nnnnnnnnnnnnnnbnnnn\n" +
					"6-8#s:#ssttshsks\n" +
					"16-20#r:#rrrrprrrjrlqrrsrrrrb\n" +
					"7-10#q:#qqqqqqqqqq\n" +
					"3-4#w:#wcbw\n" +
					"5-6#g:#tcggrxgrgvl\n" +
					"10-12#l:#kllswlmlglps\n" +
					"4-7#v:#qkvvvvqxjktkvvvjv\n" +
					"5-13#r:#rrrrqrrrrrrrrrr\n" +
					"1-2#n:#nnnnmb\n" +
					"1-8#x:#xktqbxgkkjwlt\n" +
					"3-4#k:#kskk\n" +
					"16-17#k:#kkdkkkkkkkkkkkkwk\n" +
					"10-15#n:#vnnnnnnnnqjnnknnnr\n" +
					"8-15#m:#mfmmgmmqmmmmmkmmmmmm\n" +
					"4-8#k:#kkkgkkkjkkk\n" +
					"16-17#h:#hhhhhhhhhhhlhhhqh\n" +
					"1-4#p:#ppprpppppp\n" +
					"1-9#g:#gbdxggmggrgw\n" +
					"1-5#f:#vfffff\n" +
					"2-12#d:#jzvwdmsqpdnh\n" +
					"12-13#w:#wwcwgzwwwwwhwwwwww\n" +
					"9-10#z:#zzdzzlzvgzzztzzz\n" +
					"4-5#f:#ffftff\n" +
					"8-14#x:#xxxxxxxrxxxxxx\n" +
					"1-4#r:#kgrrvrrvrr\n" +
					"3-4#w:#zkpwxkk\n" +
					"2-5#k:#tkckkfcvxkxk\n" +
					"3-9#r:#rbrrrrgrrrrkbrrr\n" +
					"3-4#t:#ttxx\n" +
					"8-11#z:#zzzzzzzzzzz\n" +
					"6-10#p:#pnwhxpmxpfskq\n" +
					"1-16#d:#dddddddddddddddgdddd\n" +
					"1-7#c:#kctcccg\n" +
					"1-5#q:#sqqqrqqq\n" +
					"14-16#f:#fjfffffqfkfffjffff\n" +
					"3-8#v:#knvrrqvtv\n" +
					"1-2#p:#ptgswlvpdnmr\n" +
					"3-5#v:#vvkmnvdwk\n" +
					"10-14#r:#rrrrrrrrrhlrwrrrd\n" +
					"2-11#f:#xffffxjfffzfffpf\n" +
					"1-5#p:#nppppppp\n" +
					"15-16#x:#xxxxxxxxxxxxxxsx\n" +
					"15-16#b:#prhbmdvwcmtzpvbb\n" +
					"11-14#t:#rngdttnzqtjtcttdvbmt\n" +
					"8-10#f:#ffvldffqfqffgf\n" +
					"1-3#r:#rzqrmz\n" +
					"7-8#n:#tntnnnntn\n" +
					"6-14#s:#qpvlfbsgswsnwsmpz\n" +
					"9-12#t:#tvwstttttttktwt\n" +
					"4-6#g:#vslqbgg\n" +
					"9-16#d:#dsdddddddrdddddhdbdd");

	@Test
	public void day2() {
	int validPasswords = 0;
		String[] split = numbers.split("\n");
		List<Dims> dims = new ArrayList<>();
		for (String s : split) {
			String[] split1 = s.split("#");
			Dims d = Dims.of(split1[0], split1[1], split1[2]);
			dims.add(d);
		}

		for (Dims dim : dims) {
			if(isvalid2(dim))
			{
				System.out.println(dim.password);
				validPasswords++;
			}
		}
		System.out.println(validPasswords);

	}

	public boolean isvalid(Dims dims) {
		int numberOfALetter = 0;
		char[] chars = dims.getPassword().toCharArray();
		for (char aChar : chars) {
			char c = dims.character.charAt(0);
			if (aChar == c) {
				numberOfALetter++;
			}
		}
		if(numberOfALetter >= dims.getFirst() && numberOfALetter <= dims.getSecond())
		{
			return true;
		}
		return false;
	}
	public boolean isvalid2(Dims dims) {
		char charAtFirst = dims.getPassword().charAt(dims.first-1);
		char charAtSecond = dims.getPassword().charAt(dims.second-1);
		char theChar = dims.character.charAt(0);
		int charsMatch = 0;
		if(charAtFirst == theChar){
			charsMatch++;
		}
		if(charAtSecond == theChar){
			charsMatch++;
		}
		return charsMatch == 1;
	}
}

